version: '3.9'

services:
  terraform:
    image: hashicorp/terraform:${TAG:-latest}
    volumes:
      - .:/app
    working_dir: /app
    command: plan
    volumes:
      - $PWD:/app/
      - $HOME/.kube/:/root/.kube/:ro
    environment:
       KUBECONFIG: ${KUBECONFIG:-$HOME/.kube/config}
       TF_INPUT: ${TF_INPUT:-1}
       TF_LOG: ${TF_LOG:-off}
    networks:
      - default
networks:
  default:
    external: true
    name: k3d
